export const COOKING_UP_THEORY = {
  pullQuote:
    'Hand someone a set of ingredients, and watch what they do with them. You\u2019ll learn more about how they think than from any other personality test.',
  paragraphs: [
    'I have a theory. Hand someone a set of ingredients, and watch what they do with them. You\u2019ll learn more about how they think than from any other personality test.',
    'My mom cooks by the book. Precision measurements. Sound techniques. Solid foundations. Respecting the recipe. There\u2019s a certain cadence to the way she cooks that makes sense when you get to know her: she thinks like a chartered accountant, moves through problems the way a financial analyst may approach a balance sheet. She\u2019s methodical, metrics-minded, with very few things left to chance and predictions. The recipe doesn\u2019t serve as a constraint — it serves as the framework she trusts.',
    'And if you couldn\u2019t already guess, my mom studied accounting in college :D!',
    'Now, what\u2019s particularly interesting is how this compares to my dad. An engineer. A researcher. And most importantly, an inventor. My dad cooks the way he solves problems: by experimenting. A dash of this, a hunch of that — maybe a bit more pepper? No, this just needs salt. He has this willingness to synthesize two seemingly incongruous dishes together and marry them in a way that truly elevates both flavors to new heights!',
    'I am particularly reminded of his Baked Ziti dish, a dish that ruled childhood Thanksgivings, Christmases, and celebrations. Between the layers of pasta, tomato sauce, cheese, and mint chutney, he\u2019d infuse \u201cThengai Mangai Pattani Sundal\u201d — a South Indian beach snack consisting of coconut, raw mangos, yellow peas, onions, and Indian seasonings. Not only did the dish borrow spice profiles from two seemingly different culinary traditions, but it also worked! And worked deliciously! That kind of thing surprised me the first time since it had no right to be that good — there was no recipe. No structure. Just a bit of this, and a bit of that, creating something that truly is irreplicable (though I have managed to come close a few times :D).',
    'When I look at my own cooking, I think I have inherited a bit of both styles. Some days, I want structure — follow the method, build strong technical foundations, respect what works. Other days, I want to push. My pestos are never quite the same twice — across several variations, I\u2019ve added orange peel for brightness, swapped pinenuts for pistachios for added richness, added goat cheese to boost creaminess, added sun-dried tomatoes for a punchier tang, mint instead of basil for flavor depth, and even blanched spinach for better color. I always taste, always adjust, always leave room for the dish to become something I didn\u2019t plan for.',
    'That tension — between the organized and the experimental — is something I recognize from the other aspects of my life as well. As a bioengineering and business major, my M.E.T. education required me to straddle the organizational frameworks of business and the experimental hypotheses built via biocomputation. And the results of this bridge showed up across the way I approached tasks. The VC investment memos. The experiments I designed. The research papers I wrote. The way I handled large-scale events.',
    'Biology itself works in a similar manner: part elegant system, part happy accident. Venture capital is the same. So is entrepreneurship. The best outcomes usually live somewhere between the person who follows the recipe and the person who\u2019s never read one.',
    'I think cooking earns its reputation as a window into personality precisely because the stakes are low enough to be honest. Nobody performs in a home kitchen the way they perform in a pre-planned interview. We default to instincts, and instinct, as it turns out, tells us a lot.',
    'So next time we are cooking with someone, or watching someone cook, pay attention. The way they handle uncertainty in a recipe is probably the way they handle uncertainty everywhere else. And that\u2019s one savory note!',
  ],
} as const;
