// Auto-generated by scripts/convert-doc-blocks.mjs — do not edit by hand
import type { ContentBlock, PostMeta, SectionNavEntry } from '@/lib/contentBlocks/types';

export const POST_META: PostMeta = {
  brand: "brainfood",
  format: "bytesize",
  title: "Speciation at Hyperscale",
  subtitle: "How fast are new AI forms appearing? And what does it mean that record creation and record extinction are happening at the exact same time?",
  seriesLabel: "Brainfood Bytesize · AI's Cambrian Explosion · Section I",
  date: "Summer 2026 · Part of the AI's Cambrian Explosion series",
  breadcrumb: "Brainfood · Bytesize · Chapter 2 · Section I",
  authorName: "Hari Parthasarathy",
  authorMeta: "M.E.T. '26 · UC Berkeley · Independent Investor & VC Scout",
  footer: "Hari Parthasarathy · M.E.T. '26, UC Berkeley · Independent Investor & VC Scout. Preview excerpt from AI's Cambrian Explosion. Full section not yet published.",
} as const;

export const CONTENT_BLOCKS: ContentBlock[] = [
  {
    type: "frameworkCard",
    title: "The Series At A Glance",
    rows: [
      {
        label: "I",
        text: "**Speciation at Hyperscale** — How fast are new forms appearing? *You are here.*",
      },
      {
        label: "II",
        text: "The Transformer as Meteor — The Ediacaran–Cambrian boundary",
      },
      {
        label: "III",
        text: "Body Plans & Exoskeletons — Infrastructure as substrate",
      },
      {
        label: "IV",
        text: "Apex Predators — Who runs the food chain?",
      },
      {
        label: "V",
        text: "Carcinization — Why every frontier model looks the same",
      },
      {
        label: "VI",
        text: "Finches and Futures — Survival of the fittest agent",
      },
    ],
  },
  {
    type: "statRow",
    stats: [
      {
        value: "52.5%",
        label: "of global VC captured by AI in 2025 — first majority year",
      },
      {
        value: "$675B+",
        label: "hyperscaler capex committed for 2026 alone",
      },
      {
        value: "1 / 3 days",
        label: "average cadence of new frontier AI model releases",
      },
    ],
  },
  {
    type: "paragraph",
    text: "The Cambrian explosion produced roughly 20 animal phyla in about 20 million years — and no new phyla have appeared in the half-billion years since. That is the biological benchmark for rapid speciation. If you want to understand how absurd the AI analog looks against it, you need to sit with that number for a moment.",
    dropCap: true,
  },
  {
    type: "paragraph",
    text: "Now look at what's happened in AI since 2022. Frontier model variants are proliferating at a rate measured in weeks. The AI Flash Report summarizes it as plainly as possible: *on average, a new AI model arrives every three days.*",
    dropCap: false,
  },
  {
    type: "section",
    id: "section-01",
    num: "01",
    pillar: "Pillar 1 — Capital Markets",
    title: "The sedimentary layer: where the nutrients came from",
    shortLabel: "Capital",
    children: [],
  },
  {
    type: "paragraph",
    text: "In the biological Cambrian, the triggering event was oxygenation. In the AI Cambrian, the equivalent is capital. Not metaphorically. Literally: the infrastructure buildout that enabled frontier-scale training required a level of capital deployment that didn't exist for any prior technology cycle.",
    dropCap: false,
  },
  {
    type: "paragraph",
    text: "In 2025, AI captured roughly 52.5% of all global venture capital — the first time any technology category has claimed majority of VC in a single year. OpenAI and Anthropic together represented about 14% of all worldwide VC dollars in 2025.",
    dropCap: false,
  },
  {
    type: "callout",
    label: "Design preview note",
    text: "This page shows the Bytesize layout with section navigation. Charts, tables, and full pillar content will ship when the Cambrian series is ready.",
  },
  {
    type: "section",
    id: "section-02",
    num: "02",
    pillar: "Pillar 2 — Across the Stack",
    title: "From foundation models to the long tail of open weights",
    shortLabel: "Stack",
    children: [],
  },
  {
    type: "paragraph",
    text: "Speciation at the model layer is visible in release cadence, open-weight proliferation, and the widening gap between frontier labs and the long tail of fine-tunes.",
    dropCap: false,
  },
  {
    type: "section",
    id: "section-03",
    num: "03",
    pillar: "Pillar 3 — Infrastructure",
    title: "The exoskeleton: compute, memory, and the cost of scale",
    shortLabel: "Infra",
    children: [],
  },
  {
    type: "paragraph",
    text: "Hyperscaler capex commitments for 2026 exceed $675B. That buildout is the exoskeleton — without it, no body plan scales.",
    dropCap: false,
  },
  {
    type: "section",
    id: "section-04",
    num: "04",
    pillar: "Pillar 4 — The Application Layer",
    title: "Where the speciation becomes visible to enterprises",
    shortLabel: "Apps",
    children: [],
  },
  {
    type: "paragraph",
    text: "Enterprise AI spend tripled in a single year. Startups captured 63% of total app-layer spend — the application layer is where speciation becomes legible to buyers.",
    dropCap: false,
  },
  {
    type: "section",
    id: "section-05",
    num: "✦",
    pillar: "What this section proves",
    title: "The question isn't how fast? — it's which of these forms survive?",
    shortLabel: "Close",
    children: [],
  },
  {
    type: "paragraph",
    text: "The speciation rate question is answered. The question every investor and founder is implicitly answering is: which body plan survives the transition to the Ordovician?",
    dropCap: false,
  },
] as const;

export const SECTION_NAV: SectionNavEntry[] = [
  {
    id: "section-01",
    num: "01",
    shortLabel: "Capital",
    pillar: "Pillar 1 — Capital Markets",
    title: "The sedimentary layer: where the nutrients came from",
  },
  {
    id: "section-02",
    num: "02",
    shortLabel: "Stack",
    pillar: "Pillar 2 — Across the Stack",
    title: "From foundation models to the long tail of open weights",
  },
  {
    id: "section-03",
    num: "03",
    shortLabel: "Infra",
    pillar: "Pillar 3 — Infrastructure",
    title: "The exoskeleton: compute, memory, and the cost of scale",
  },
  {
    id: "section-04",
    num: "04",
    shortLabel: "Apps",
    pillar: "Pillar 4 — The Application Layer",
    title: "Where the speciation becomes visible to enterprises",
  },
  {
    id: "section-05",
    num: "✦",
    shortLabel: "Close",
    pillar: "What this section proves",
    title: "The question isn't how fast? — it's which of these forms survive?",
  },
] as const;
