export const FIGHT_OR_FLIGHT = {
  pullQuote:
    'The small fights were where they found their language. Their rhythms, their daily groove. The specific, irreplaceable texture of that particular relationship, and no other.',
  paragraphs: [
    'There is a particular kind of wisdom that only seems to show up at the end of things.',
    'I was recently talking to an elderly woman who had just lost her husband a few months back. While talking about his passing and what had happened that day, somewhere in the middle of a conversation on their banter and arguments, she smiled. Not exactly the smile of a person fully at peace, but rather the kind that came from bittersweet pain. A quiet acceptance. A newfound appreciation for their shared time. A nostalgic reminder of the life that had been.',
    'She reminisced on the way they\u2019d lock up over something small and insignificant. How they would walk quietly in silence, unwilling to yield their position, yet somehow content with the presence of one another. The same morning routines of coffee and the newspaper. Even that morning, he had taken their granddaughter for a walk in the stroller, despite her constant requests that he rest up.',
    'What I found interesting was that she wasn\u2019t just mourning these arguments or seeing them as shortcomings in their relationship. She was reminiscing on them, as shared memories of a better time together.',
    'That hit me. Because, in the moment, these arguments, these debates, these disagreements — they all feel like friction. Something to get through, something to challenge, and most often, something to win. We are so focused on being right, on being respected, on being validated, that we treat the whole uncomfortable mess as something of a cost. Something to minimize, not to recognize.',
    'And frankly, this realization isn\u2019t just tied to the nostalgia that comes with losing a loved one. Two weeks ago, at graduation, Yamini Rangan — the CEO of HubSpot, and commencement speaker — stood in front of an audience of Haas graduates, and said it plainly: Relish the Discomfort. It stuck with me in a way I didn\u2019t fully expect.',
    'Maybe because, in the back of my mind, I had been sitting with that elderly woman\u2019s story. Maybe because that line did something rare — it wasn\u2019t a recipe for future success, or a look backward at the past. It pertained to the present. To right now. At the friction we feel. The conversations we try to end quickly instead of actually pausing to have. Her words served as a reminder to stay present in the mess, not just in the moments that feel worth remembering.',
    'And it seemed to capture, almost perfectly, what that elderly woman had spent a lifetime learning — that the uncomfortable parts of a journey weren\u2019t in the way of life. They were an integral part of it.',
    'Because that woman wasn\u2019t sorting her memories into the best days and the worst days. She was remembering them together, as the same days. The small banters, the routine stubbornness — these were texture. It was proof of a deep, meaningful, close relationship, one where two people worked out, in real time, how to work with each other, how to be near each other. Those uncomfortable notes mattered more than they realized.',
    'I think about how much energy goes into avoiding the discomfort. In the arguments. In the relationships. In the daily frictions of being a friend, a confidant, a mentor, or a mentee. And I wonder how much of what we are trying to smooth over is actually the memories we\u2019d want to cherish one day.',
    'Life doesn\u2019t allow us to just keep the good parts and discard the rest — our brains are hardwired for recall indiscriminately. To remember, to reminisce, to overthink, to underappreciate. All these memories come as a package.',
    'And, if we are lucky enough to have people worth fighting for, then the move might not be to win faster. It might be to pause, soak it all in, and notice that we are in it all.',
  ],
} as const;
